version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=YourStrongPassword!123
      - MYSQL_DATABASE=AccesoAlimentario
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=YourStrongPassword!123
    ports:
      - "3306:3306"
    networks:
      - accesodb

  accesoalimentario:
    build:
      context: .
      dockerfile: Dockerfile
    image: accesoalimentario:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_SERVER=mysql
      - DB_NAME=AccesoAlimentario
      - DB_USER=dev
      - DB_PASSWORD=YourStrongPassword!123
    ports:
      - "5000:8085" # Mapea el puerto 8080 del contenedor al puerto 5000 del host
    depends_on:
      - mysql
    networks:
      - accesodb
      - default
  
  front:
      build:
        context: ./AccesoAlimentario.Frontend
        dockerfile: Dockerfile
        args:
          - NEXT_PUBLIC_API_URL=http://localhost:5000/api
      image: accesoalimentario-frontend:latest
      ports:
        - "3000:3000"      
      networks:
        - default
  
  recomendacionesApi:
    build:
        context: ./ServicioRecomendaciones
        dockerfile: Dockerfile
    image: recomendacionesapi:latest
    environment:
      - COLABORADORES_API_URL=http://accesoalimentario:8085/api/colaboradores
    ports:
        - "8080:8080"
    networks:
        - default

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ server port
      - "15672:15672" # Management console
    networks:
      - default
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

networks:
  accesodb:
    driver: bridge
