version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=YourStrongPassword!123
      - MYSQL_DATABASE=AccesoAlimentario
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=YourStrongPassword!123
    ports:
      - "3306:3306"
    networks:
      - accesodb

  accesoalimentario:
    build:
      context: .
      dockerfile: Dockerfile
    image: accesoalimentario:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=AccesoAlimentario
      - DB_USER=dev
      - DB_PASSWORD=YourStrongPassword!123
      - GOOGLE_CLIENT_ID=478798027963-88ordqooemog7dh7dekdvs6krb00bkp4.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    ports:
      - "5000:8085" # Mapea el puerto 8080 del contenedor al puerto 5000 del host
    depends_on:
      - mysql
    networks:
      - accesodb
      - default


networks:
  accesodb:
    driver: bridge
