public_subnet_name = "acceso-alimentario-public"
domain_zone_id     = "Z00362715JGFXPFE3OAC"
vpc_name           = "acceso-alimentario"
domain_record      = "acceso-alimentario.opsconsultingservices.com"
alb_name           = "acceso-alimentario"
region             = "sa-east-1"