name: Deployment
run-name: ${{ github.event.head_commit.message }}

on: [push]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  backend_s3_bucket: "acceso-alimentario"
  backend_dynamodb_table: "acceso-alimentario-terraform-state-lock"
  repo_name: "acceso-alimentario/releases"
  vpc_name: "acceso-alimentario"
  domain_record: "acceso-alimentario.opsconsultingservices.com"
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    outputs:
      image_tag: ${{ steps.build-publish.outputs.image_tag }}
      full_image: ${{ steps.build-publish.outputs.full_image }}
    steps:
      
      - name: Clone the repository
        uses: actions/checkout@v4

      
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::034781041905:role/GhActionsRunner
          role-session-name: ${{ github.actor }}-session
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          
      - name: prepare ECR repo name based on the Github repository
        shell: bash
        run: |
          set -eux
          # lowercase the name
          repo="${{ env.repo_name }}"
          # replace / with _
          echo "ECR_REPO_NAME=${repo//\//_}" >> $GITHUB_ENV

      - name: TF init
        shell: bash
        run: |
          set -eux
          modules=(ecr vpc alb)
          for module in "${modules[@]}"; do
            echo "module: $module" 
            cd $module 
            terraform init -upgrade -migrate-state \
              -backend-config='skip_metadata_api_check=true' \
              -backend-config='skip_region_validation=true' \
              -backend-config='skip_credentials_validation=true' \
              -backend-config='region=${{ secrets.AWS_REGION }}' \
              -backend-config='bucket=${{ env.backend_s3_bucket }}' \
              -backend-config='key=${module}/terraform-${{ env.ECR_REPO_NAME }}.tfstate' \
              -backend-config='dynamodb_table=${{ env.backend_dynamodb_table }}'            
          done            
        working-directory: "./deployment"
        
      - name: Create ECR repo [TF apply]
        shell: bash
        run: |
          set -eux
          terraform apply -var 'repository_name=${{ env.ECR_REPO_NAME }}' -var 'lifecycle_policy_file=../ecr_policy.json' -auto-approve
        working-directory: "./deployment/ecr"
        
      - name: Create VPC [TF apply]
        shell: bash
        run: |
          set -eux
          terraform apply -var 'vpc_name=${{ env.vpc_name }}' -auto-approve
        working-directory: "./deployment/vpc"
        
      - name: Create ALB [TF apply]
        shell: bash
        run: |
          set -eux
          terraform apply -var 'vpc_name=${{ env.vpc_name }}' -var 'public_subnet_name=${{ env.vpc_name }}-public' -var 'domain_zone_id=${{ secrets.ROUTE53_ZONE_ID }}' -var 'domain_record=${{ env.domain_record }}' -auto-approve
        working-directory: "./deployment/alb"
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_ACCOUNT_ID }}
          
      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash        
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build "." -f "./Dockerfile" -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "image_tag=$IMAGE_TAG" 
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"