name: Deployment
run-name: ${{ github.event.head_commit.message }}

on: [workflow_dispatch]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  backend_s3_bucket: "acceso-alimentario"
  backend_dynamodb_table: "acceso-alimentario-terraform-state-lock"
  repo_name: "acceso-alimentario/releases"
  vpc_name: "acceso-alimentario"
  domain_record: "acceso-alimentario.opsconsultingservices.com"
  ECS_TASK_DEFINITION: "deployment/task_def.json"
  alb_name: "acceso-alimentario"
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    if: github.event_name == 'workflow_dispatch' # Ensures it only runs manually
    outputs:
      image_tag: ${{ steps.build-publish.outputs.image_tag }}
      full_image: ${{ steps.build-publish.outputs.full_image }}
    steps:
      
      - name: Clone the repository
        uses: actions/checkout@v4

      
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::034781041905:role/GhActionsRunner
          role-session-name: ${{ github.actor }}-session
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          
      - name: prepare ECR repo name based on the Github repository
        shell: bash
        run: |
          set -eux
          # lowercase the name
          repo="${{ env.repo_name }}"
          # replace / with _
          echo "ECR_REPO_NAME=${repo//\//_}" >> $GITHUB_ENV

      - name: TF init
        shell: bash
        run: |
          set -eux
          modules=(ecr vpc alb ecs rds)
          
          for module in "${modules[@]}"; do
            echo "module: $module" 
            cd $module 
            terraform init -upgrade -migrate-state \
              -backend-config='skip_metadata_api_check=true' \
              -backend-config='skip_region_validation=true' \
              -backend-config='skip_credentials_validation=true' \
              -backend-config='region=${{ secrets.AWS_REGION }}' \
              -backend-config='bucket=${{ env.backend_s3_bucket }}' \
              -backend-config="key=$module/terraform-${{ env.ECR_REPO_NAME }}.tfstate" \
              -backend-config='dynamodb_table=${{ env.backend_dynamodb_table }}'
            cd ..
          done            
        working-directory: "./deployment"
        
      - name: Create ECR repo [TF apply]
        shell: bash
        run: |
          set -eux 
          terraform apply -var-file="prod.tfvars" -auto-approve
        working-directory: "./deployment/ecr"

      - name: Create VPC [TF apply]
        shell: bash
        run: |
          set -eux
          terraform apply -var-file="prod.tfvars" -auto-approve
        working-directory: "./deployment/vpc"

      - name: Create ALB [TF apply]
        shell: bash
        run: |
          set -eux
          terraform apply -var-file="prod.tfvars" -auto-approve
        working-directory: "./deployment/alb"
        
      - name: Create ECS Cluster [TF apply]
        id: ecs_cluster
        shell: bash
        run: |
          set -eux
          terraform apply -var-file="prod.tfvars" -auto-approve
          echo "task_role_arn=$(terraform output -raw task_role_arn)" >> $GITHUB_OUTPUT
          echo "task_execution_role_arn=$(terraform output -raw task_execution_role_arn)" >> $GITHUB_OUTPUT
        working-directory: "./deployment/ecs"
        
      - name: Create RDS [TF apply]
        shell: bash
        run: |
          set -eux
          terraform apply -var-file="prod.tfvars" -var 'region=${{ secrets.AWS_REGION }}' -auto-approve
        working-directory: "./deployment/rds"
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_ACCOUNT_ID }}
          
      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash        
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build "." -f "./Dockerfile" -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "image_tag=$IMAGE_TAG"           
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV
          
      - name: Build, tag, and push frontend to Amazon ECR
        id: build-publish-frontend
        shell: bash        
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "acceso-alimentario-frontend"
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build "." -f "./Dockerfile" -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "image_tag_front=$IMAGE_TAG"           
          echo "full_image_front=$ECR_REGISTRY/$ECR_REPOSITORY/front:$IMAGE_TAG"
          echo "full_image_front=$ECR_REGISTRY/$ECR_REPOSITORY/front:$IMAGE_TAG" >> $GITHUB_ENV
        working-directory: "./AccesoAlimentario.Frontend"

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: "accesoalimentario"
          image: ${{ env.full_image }}
      
      - name: Update Task def to use the deployed TASK role and ECS task execution role
        run: |
          set -eux
          if [ -z "${{ steps.ecs_cluster.outputs.task_role_arn }}" ] || [ -z "${{ steps.ecs_cluster.outputs.task_execution_role_arn }}" ]; then
            echo "ERROR: Required ECS role ARNs are missing!"
            exit 1
          fi
          sed -i "s#TASK_ROLE_ARN#${{ steps.ecs_cluster.outputs.task_role_arn }}#" "${{ steps.task-def.outputs.task-definition }}"
          sed -i "s#TASK_EXECUTION_ROLE_ARN#${{ steps.ecs_cluster.outputs.task_execution_role_arn }}#" "${{ steps.task-def.outputs.task-definition }}"
          sed -i "s#IMAGE_FRONT#${{ env.full_image_front }}#" "${{ steps.task-def.outputs.task-definition }}"
          

      - name: Echo the new ECS task definition
        run: cat "${{ steps.task-def.outputs.task-definition }}"
        
      - name: Deploy Amazon ECS task definition
        id: deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: "accesoalimentario"
          cluster: "accesoalimentario"
          wait-for-service-stability: false   