using AccesoAlimentario.Core.Entities;
using AccesoAlimentario.Core.Entities.Autorizaciones;
using AccesoAlimentario.Core.Entities.Contribuciones;
using AccesoAlimentario.Core.Entities.Direcciones;
using AccesoAlimentario.Core.Entities.Heladeras;
using AccesoAlimentario.Core.Entities.Incidentes;
using AccesoAlimentario.Core.Entities.MediosContacto;
using AccesoAlimentario.Core.Entities.Notificaciones;
using AccesoAlimentario.Core.Entities.Personas;
using AccesoAlimentario.Core.Entities.Personas.DocumentosIdentidad;
using AccesoAlimentario.Core.Entities.Personas.PersonaJuridica;
using AccesoAlimentario.Core.Entities.Personas.Tecnicos;
using AccesoAlimentario.Core.Entities.Premios;
using AccesoAlimentario.Core.Entities.Roles;
using AccesoAlimentario.Core.Entities.Sensores;
using AccesoAlimentario.Core.Entities.SuscripcionesColaboradores;
using AccesoAlimentario.Core.Entities.Tarjetas;
using AccesoAlimentario.Core.Entities.Usuarios;

namespace AccesoAlimentario.Core.DAL;

public class UnitOfWork(AppDbContext context)
{
    private GenericRepository<AccesoHeladera> _accesoHeladeraRepository = null!;
    private GenericRepository<AutorizacionManipulacionHeladera> _autorizacionManipulacionHeladeraRepository = null!;
    private GenericRepository<AdministracionHeladera> _administracionHeladeraRepository = null!;
    private GenericRepository<DistribucionViandas> _distribucionViandasRepository = null!;
    private GenericRepository<DonacionMonetaria> _donacionMonetariaRepository = null!;
    private GenericRepository<DonacionVianda> _donacionViandaRepository = null!;
    private GenericRepository<FormaContribucion> _formaContribucionRepository = null!;
    private GenericRepository<OfertaPremio> _ofertaPremioRepository = null!;
    private GenericRepository<RegistroPersonaVulnerable> _registroPersonaVulnerableRepository = null!;
    private GenericRepository<Direccion> _direccionRepository = null!;
    private GenericRepository<DocumentoIdentidad> _documentoIdentidadRepository = null!;
    private GenericRepository<Heladera> _heladeraRepository = null!;
    private GenericRepository<ModeloHeladera> _modeloHeladeraRepository = null!;
    private GenericRepository<PuntoEstrategico> _puntoEstrategicoRepository = null!;
    private GenericRepository<Vianda> _viandaRepository = null!;
    private GenericRepository<ViandaEstandar> _viandaEstandarRepository = null!;
    private GenericRepository<Alerta> _alertaRepository = null!;
    private GenericRepository<FallaTecnica> _fallaTecnicaRepository = null!;
    private GenericRepository<Incidente> _incidenteRepository = null!;
    private GenericRepository<VisitaTecnica> _visitaTecnicaRepository = null!;
    private GenericRepository<Email> _emailRepository = null!;
    private GenericRepository<MedioContacto> _medioContactoRepository = null!;
    private GenericRepository<Telefono> _telefonoRepository = null!;
    private GenericRepository<Whatsapp> _whatsappRepository = null!;
    private GenericRepository<Notificacion> _notificacionRepository = null!;
    private GenericRepository<PersonaHumana> _personaHumanaRepository = null!;
    private GenericRepository<PersonaJuridica> _personaJuridicaRepository = null!;
    private GenericRepository<Premio> _premioRepository = null!;
    private GenericRepository<AreaCobertura> _areaCoberturaRepository = null!;
    private GenericRepository<Colaborador> _colaboradorRepository = null!;
    private GenericRepository<PersonaVulnerable> _personaVulnerableRepository = null!;
    private GenericRepository<Rol> _rolRepository = null!;
    private GenericRepository<Tecnico> _tecnicoRepository = null!;
    private GenericRepository<UsuarioSistema> _usuarioSistemaRepository = null!;
    private GenericRepository<RegistroMovimiento> _registroMovimientoRepository = null!;
    private GenericRepository<RegistroTemperatura> _registroTemperaturaRepository = null!;
    private GenericRepository<SensorMovimiento> _sensorMovimientoRepository = null!;
    private GenericRepository<SensorTemperatura> _sensorTemperaturaRepository = null!;
    private GenericRepository<Suscripcion> _suscripcionRepository = null!;
    private GenericRepository<SuscripcionExcedenteViandas> _suscripcionExcedenteViandasRepository = null!;
    private GenericRepository<SuscripcionFaltanteViandas> _suscripcionFaltanteViandasRepository = null!;
    private GenericRepository<SuscripcionIncidenteHeladera> _suscripcionIncidenteHeladeraRepository = null!;
    private GenericRepository<Tarjeta> _tarjetaRepository = null!;
    private GenericRepository<TarjetaColaboracion> _tarjetaColaboracionRepository = null!;
    private GenericRepository<TarjetaConsumo> _tarjetaConsumoRepository = null!;

    /* ------------------------------------ */

    public GenericRepository<AccesoHeladera> AccesoHeladeraRepository => _accesoHeladeraRepository ??= new GenericRepository<AccesoHeladera>(context);
    public GenericRepository<AutorizacionManipulacionHeladera> AutorizacionManipulacionHeladeraRepository => _autorizacionManipulacionHeladeraRepository ??= new GenericRepository<AutorizacionManipulacionHeladera>(context);
    public GenericRepository<AdministracionHeladera> AdministracionHeladeraRepository => _administracionHeladeraRepository ??= new GenericRepository<AdministracionHeladera>(context);
    public GenericRepository<DistribucionViandas> DistribucionViandasRepository => _distribucionViandasRepository ??= new GenericRepository<DistribucionViandas>(context);
    public GenericRepository<DonacionMonetaria> DonacionMonetariaRepository => _donacionMonetariaRepository ??= new GenericRepository<DonacionMonetaria>(context);
    public GenericRepository<DonacionVianda> DonacionViandaRepository => _donacionViandaRepository ??= new GenericRepository<DonacionVianda>(context);
    public GenericRepository<FormaContribucion> FormaContribucionRepository => _formaContribucionRepository ??= new GenericRepository<FormaContribucion>(context);
    public GenericRepository<OfertaPremio> OfertaPremioRepository => _ofertaPremioRepository ??= new GenericRepository<OfertaPremio>(context);
    public GenericRepository<RegistroPersonaVulnerable> RegistroPersonaVulnerableRepository => _registroPersonaVulnerableRepository ??= new GenericRepository<RegistroPersonaVulnerable>(context);
    public GenericRepository<Direccion> DireccionRepository => _direccionRepository ??= new GenericRepository<Direccion>(context);
    public GenericRepository<DocumentoIdentidad> DocumentoIdentidadRepository => _documentoIdentidadRepository ??= new GenericRepository<DocumentoIdentidad>(context);
    public GenericRepository<Heladera> HeladeraRepository => _heladeraRepository ??= new GenericRepository<Heladera>(context);
    public GenericRepository<ModeloHeladera> ModeloHeladeraRepository => _modeloHeladeraRepository ??= new GenericRepository<ModeloHeladera>(context);
    public GenericRepository<PuntoEstrategico> PuntoEstrategicoRepository => _puntoEstrategicoRepository ??= new GenericRepository<PuntoEstrategico>(context);
    public GenericRepository<Vianda> ViandaRepository => _viandaRepository ??= new GenericRepository<Vianda>(context);
    public GenericRepository<ViandaEstandar> ViandaEstandarRepository => _viandaEstandarRepository ??= new GenericRepository<ViandaEstandar>(context);
    public GenericRepository<Alerta> AlertaRepository => _alertaRepository ??= new GenericRepository<Alerta>(context);
    public GenericRepository<FallaTecnica> FallaTecnicaRepository => _fallaTecnicaRepository ??= new GenericRepository<FallaTecnica>(context);
    public GenericRepository<Incidente> IncidenteRepository => _incidenteRepository ??= new GenericRepository<Incidente>(context);
    public GenericRepository<VisitaTecnica> VisitaTecnicaRepository => _visitaTecnicaRepository ??= new GenericRepository<VisitaTecnica>(context);
    public GenericRepository<Email> EmailRepository => _emailRepository ??= new GenericRepository<Email>(context);
    public GenericRepository<MedioContacto> MedioContactoRepository => _medioContactoRepository ??= new GenericRepository<MedioContacto>(context);
    public GenericRepository<Telefono> TelefonoRepository => _telefonoRepository ??= new GenericRepository<Telefono>(context);
    public GenericRepository<Whatsapp> WhatsappRepository => _whatsappRepository ??= new GenericRepository<Whatsapp>(context);
    public GenericRepository<Notificacion> NotificacionRepository => _notificacionRepository ??= new GenericRepository<Notificacion>(context);
    public GenericRepository<PersonaHumana> PersonaHumanaRepository => _personaHumanaRepository ??= new GenericRepository<PersonaHumana>(context);
    public GenericRepository<PersonaJuridica> PersonaJuridicaRepository => _personaJuridicaRepository ??= new GenericRepository<PersonaJuridica>(context);
    public GenericRepository<Premio> PremioRepository => _premioRepository ??= new GenericRepository<Premio>(context);
    public GenericRepository<AreaCobertura> AreaCoberturaRepository => _areaCoberturaRepository ??= new GenericRepository<AreaCobertura>(context);
    public GenericRepository<Colaborador> ColaboradorRepository => _colaboradorRepository ??= new GenericRepository<Colaborador>(context);
    public GenericRepository<PersonaVulnerable> PersonaVulnerableRepository => _personaVulnerableRepository ??= new GenericRepository<PersonaVulnerable>(context);
    public GenericRepository<Rol> RolRepository => _rolRepository ??= new GenericRepository<Rol>(context);
    public GenericRepository<Tecnico> TecnicoRepository => _tecnicoRepository ??= new GenericRepository<Tecnico>(context);
    public GenericRepository<UsuarioSistema> UsuarioSistemaRepository => _usuarioSistemaRepository ??= new GenericRepository<UsuarioSistema>(context);
    public GenericRepository<RegistroMovimiento> RegistroMovimientoRepository => _registroMovimientoRepository ??= new GenericRepository<RegistroMovimiento>(context);
    public GenericRepository<RegistroTemperatura> RegistroTemperaturaRepository => _registroTemperaturaRepository ??= new GenericRepository<RegistroTemperatura>(context);
    public GenericRepository<SensorMovimiento> SensorMovimientoRepository => _sensorMovimientoRepository ??= new GenericRepository<SensorMovimiento>(context);
    public GenericRepository<SensorTemperatura> SensorTemperaturaRepository => _sensorTemperaturaRepository ??= new GenericRepository<SensorTemperatura>(context);
    public GenericRepository<Suscripcion> SuscripcionRepository => _suscripcionRepository ??= new GenericRepository<Suscripcion>(context);
    public GenericRepository<SuscripcionExcedenteViandas> SuscripcionExcedenteViandasRepository => _suscripcionExcedenteViandasRepository ??= new GenericRepository<SuscripcionExcedenteViandas>(context);
    public GenericRepository<SuscripcionFaltanteViandas> SuscripcionFaltanteViandasRepository => _suscripcionFaltanteViandasRepository ??= new GenericRepository<SuscripcionFaltanteViandas>(context);
    public GenericRepository<SuscripcionIncidenteHeladera> SuscripcionIncidenteHeladeraRepository => _suscripcionIncidenteHeladeraRepository ??= new GenericRepository<SuscripcionIncidenteHeladera>(context);
    public GenericRepository<Tarjeta> TarjetaRepository => _tarjetaRepository ??= new GenericRepository<Tarjeta>(context);
    public GenericRepository<TarjetaColaboracion> TarjetaColaboracionRepository => _tarjetaColaboracionRepository ??= new GenericRepository<TarjetaColaboracion>(context);
    public GenericRepository<TarjetaConsumo> TarjetaConsumoRepository => _tarjetaConsumoRepository ??= new GenericRepository<TarjetaConsumo>(context);
}